# Merged vs Non-Merged — analiza offline

Notebook działa **bez uruchomionych serwisów** — importuje funkcje z `backend/app.py`
i modele z `similarity_backend/app.py` bezpośrednio w procesie.

**Struktura plików:**
```
./                                 ← notebook + analyze_merged_vs_nonmerged.py
./backend/app.py
./similarity_backend/app.py
```

**Pierwsze uruchomienie** — ładowanie modeli BGE-M3 + BGE-reranker trwa ~30s.
Kolejne komórki korzystają z cache, modele nie są ładowane ponownie.

## 1. Parametry

In [2]:
# ── ZMIEŃ TU ──────────────────────────────────────────────────────────────────

DATASET            = "gutenqa_all"   # slug datasetu (merged lub non-merged)
DATA_ROOT          = "./data"       # ścieżka do katalogu z pirb/ i processed/

SCORE_TOL          = 0.02            # tolerancja retrieval score ±
RERANKER_THRESHOLD = 0.5             # minimalny score rerankera dla merged chunków

VERBOSE            = False           # True = drukuj każdy case na bieżąco

## 2. Import modułu analizy

In [3]:
import importlib.util, sys, json
from pathlib import Path
from dataclasses import asdict

# Remove cached module so re-running this cell picks up any changes to the .py file
sys.modules.pop("analysis", None)

spec = importlib.util.spec_from_file_location("analysis", Path("analyze_merged_vs_nonmerged.py"))
mod  = importlib.util.module_from_spec(spec)
sys.modules["analysis"] = mod   # register before exec (same fix as inside the script)
spec.loader.exec_module(mod)
analysis = mod

merged_slug, nonmerged_slug = analysis._get_pair_slugs(DATASET)
print(f"Merged dataset    : {merged_slug}")
print(f"Non-merged dataset: {nonmerged_slug}")
print(f"Data root         : {Path(DATA_ROOT).resolve()}")

Merged dataset    : gutenqa_all_merged
Non-merged dataset: gutenqa_all
Data root         : C:\Users\admin\Downloads\chunker-analyzer\chunker-analyzer-v8\data

## 3. Sprawdź dostępne datasety (opcjonalnie)

In [4]:
b = analysis._load_backend(DATA_ROOT)
groups = b.group_experiments_by_dataset()
print(f"Dostępne datasety ({len(groups)}):")
for slug, exps in sorted(groups.items()):
    chunkers = [b.get_experiment_metadata(e).get("chunker_name", e) for e in exps]
    print(f"  {slug}  [{', '.join(chunkers)}]")

Dostępne datasety (11):
  gutenqa_all  [fixed_size, max_min_chunker, sequential_hac_chunker, recursive_semantic, graphseg]
  gutenqa_all_merged  [fixed_size, max_min_chunker, recursive_semantic, sequential_hac_chunker]
  literaryqa_test  [fixed_size, max_min_chunker, sequential_hac_chunker, recursive_semantic]
  natural_questions_validation_300_docs  [fixed_size, max_min_chunker, sequential_hac_chunker, text_tiling, recursive_semantic, graphseg, lumberchunker_api, dense_x_retrieval]
  novelqa_public  [fixed_size, max_min_chunker, recursive_semantic, sequential_hac_chunker]
  poquad_validation  [fixed_size, max_min_chunker, sequential_hac_chunker, text_tiling, recursive_semantic, graphseg, lumberchunker_api, dense_x_retrieval]
  poquad_validation_merged  [fixed_size, max_min_chunker, recursive_semantic, sequential_hac_chunker]
  qasper_test  [fixed_size, max_min_chunker, sequential_hac_chunker, text_tiling, graphseg, lumberchunker, recursive_semantic, lumberchunker_api, dense_x_retrieval]
  squad_train  [fixed_size, max_min_chunker, sequential_hac_chunker, graphseg, lumberchunker, recursive_semantic, dense_x_retrieval]
  triviaqa_span_annotated_test_artificial_1000_docs  [fixed_size, max_min_chunker, sequential_hac_chunker, graphseg, lumberchunker, recursive_semantic, dense_x_retrieval]
  triviaqa_span_annotated_test_artificial_1000_docs_merged  [fixed_size, max_min_chunker, recursive_semantic, sequential_hac_chunker, dense_x_retrieval]

## 4. Załaduj modele ML (jednorazowo ~30s)

In [5]:
# Jawne załadowanie — żeby nie zaskoczyło podczas analizy
sim = analysis._load_similarity()
print(f"Device: {sim.device}")
print(f"Embed model : {sim.embed_model}")
print(f"Reranker    : {sim.reranker}")

Loading ML models (BGE-M3 + BGE-reranker) — first call only, ~30s…

c:\Users\admin\Downloads\chunker-analyzer\chunker-analyzer-v8\similarity_backend\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Using device: cuda
  Models loaded on device: cuda
Device: cuda
Embed model : SentenceTransformer(
  (0): Transformer({'max_seq_length': 8192, 'do_lower_case': False, 'architecture': 'XLMRobertaModel'})
  (1): Pooling({'word_embedding_dimension': 1024, 'pooling_mode_cls_token': True, 'pooling_mode_mean_tokens': False, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)
Reranker    : <FlagEmbedding.inference.reranker.encoder_only.base.BaseReranker object at 0x000001943AE3C2C0>

## 5. Uruchom analizę

In [6]:
cases = analysis.analyze(
    dataset_slug       = DATASET,
    data_root          = DATA_ROOT,
    score_tol          = SCORE_TOL,
    reranker_threshold = RERANKER_THRESHOLD,
    verbose            = VERBOSE,
)
print(f"\nZnaleziono łącznie: {len(cases)} pasujących przypadków.")

Merged dataset    : gutenqa_all_merged
Non-merged dataset: gutenqa_all
Data root         : C:\Users\admin\Downloads\chunker-analyzer\chunker-analyzer-v8\data

Loading queries for merged dataset…
  2981 queries
Loading queries for non-merged dataset…
  2981 queries
Loading metrics…
  Chunkers: ['fixed_size', 'max_min_chunker', 'recursive_semantic', 'sequential_hac_chunker']


── Chunker: fixed_size ─────────────────────────────

pre tokenize:   0%|          | 0/1 [00:00<?, ?it/s]You're using a XLMRobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 330.31it/s]
c:\Users\admin\Downloads\chunker-analyzer\chunker-analyzer-v8\similarity_backend\.venv\Lib\site-packages\transformers\tokenization_utils_base.py:2888: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.46it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.83it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 492.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.79it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 236.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 882.45it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 526.46it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1007.28it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 250.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 505.52it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 250.06it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.41it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.41it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 490.28it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 493.51it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 399.61it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 712.71it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.88it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 995.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 997.93it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 981.35it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 403.26it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1008.00it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 663.87it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 693.16it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 896.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 479.79it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 693.50it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 562.84it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 332.46it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 991.80it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1003.66it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.60it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.36it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 662.29it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.32it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.37it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.41it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.98it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 996.51it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.59it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.28it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 662.71it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 374.99it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 664.50it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.73it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1016.55it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 655.56it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1020.51it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.27it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.44it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 649.98it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.36it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1014.59it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.50it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 656.90it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.68it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 482.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.12it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 653.01it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 697.31it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 334.10it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 453.29it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1019.52it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 661.25it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.55it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 995.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 430.10it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.36it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.74it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.07it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.39it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 993.91it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.36it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.98it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 493.62it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 973.38it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.79it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 401.25it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 533.42it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.83it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.83it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 398.47it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1125.38it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.62it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.76it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 399.12it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 475.71it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.35it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.57it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 497.90it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.88it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 984.81it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1111.07it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 645.18it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.51it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 494.79it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 983.42it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 398.21it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 665.45it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 328.53it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.87it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.10it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1015.57it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.58it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 531.46it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.06it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 490.16it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1003.42it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.70it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1013.12it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 890.89it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 494.49it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 527.59it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 484.44it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1129.93it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 669.70it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 402.18it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1017.05it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 398.02it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1041.03it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1004.62it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1014.34it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 675.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.63it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.17it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.27it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1016.06it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 552.25it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 389.52it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 330.83it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.64it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.22it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 531.46it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 974.29it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 961.11it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1003.90it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.62it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1044.92it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.49it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.57it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.28it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1015.32it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 975.42it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1006.55it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1014.10it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 973.83it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 516.22it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.79it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 533.36it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 447.20it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 995.09it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 482.94it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1005.83it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 399.46it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 510.75it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 497.54it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 948.51it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 987.13it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 847.85it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 805.51it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 497.66it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 381.44it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 526.92it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 507.17it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.64it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 388.65it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 496.90it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 799.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.07it/s]

  [2981/2981] q.999…
  Found 33 matching cases for fixed_size

── Chunker: max_min_chunker ─────────────────────────────

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 487.71it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 717.34it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 538.49it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1156.73it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1003.90it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1007.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 809.87it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 971.35it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 880.05it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.47it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1048.05it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 318.35it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 410.60it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 996.27it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1143.17it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1125.38it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 710.42it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.36it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1157.37it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 789.89it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 932.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 496.66it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.56it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.79it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.38it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1005.59it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 523.11it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 820.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 400.56it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 816.33it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 988.76it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 532.07it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 487.31it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 416.14it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 497.84it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 416.60it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 684.45it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1005.11it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 381.72it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 760.11it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1003.42it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1003.66it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 396.59it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.50it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.11it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1002.46it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1007.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.92it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.73it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 384.90it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.70it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.40it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 99.63it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1021.51it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 991.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.14it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 992.26it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1012.38it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.73it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 505.76it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 341.08it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1060.51it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1011.89it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.72it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 921.83it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1072.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 986.43it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.45it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 958.48it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1011.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 517.94it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1005.11it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 694.19it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 337.11it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.92it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 995.80it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 969.78it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 511.50it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1010.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1016.06it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 497.72it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1003.18it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1041.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 323.66it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 508.59it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 512.94it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.17it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 745.52it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1144.42it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1056.23it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 505.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 494.20it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 414.13it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 419.18it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1035.37it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 793.02it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 496.02it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 494.49it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.10it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 474.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 385.79it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.51it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 684.23it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 774.29it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 415.77it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.98it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 423.15it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 992.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 447.58it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1010.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 764.13it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1842.84it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 741.57it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1002.22it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1151.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.55it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 947.22it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.93it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.60it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 330.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1003.42it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 99.94it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.55it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 69.18it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 763.29it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 476.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 519.23it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.62it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1022.50it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.56it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.00it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1044.40it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 971.58it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1014.10it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1015.08it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.92it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1018.28it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.56it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.76it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 983.42it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 493.85it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.25it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.91it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.60it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.03it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1006.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 506.44it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.27it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 900.84it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.17it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 976.10it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 492.93it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 972.71it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 516.99it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1008.49it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.61it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 996.75it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 400.79it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.12it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1145.98it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 283.09it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.38it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 199.98it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.76it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.68it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1124.18it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 249.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.36it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 111.08it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 496.84it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 529.18it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 331.70it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 489.19it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.33it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 331.70it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1146.30it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 164.12it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 193.13it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 890.32it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 283.94it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 250.02it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 496.54it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.62it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 928.15it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 988.52it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 527.39it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1020.76it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.12it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 985.50it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 894.69it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1014.83it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 276.29it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 338.85it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 516.35it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.36it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 774.57it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 497.37it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 491.89it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1008.97it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 496.78it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.17it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.95it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1042.84it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1084.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 496.84it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.29it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1008.97it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 484.33it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 493.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 783.69it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 507.54it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 513.50it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 497.19it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1006.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 942.75it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1010.92it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.46it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.64it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 513.76it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.70it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 332.96it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.69it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 336.16it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1082.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 523.57it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 535.53it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 958.70it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 514.39it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 996.75it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 746.98it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1065.08it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.17it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.41it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.41it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1015.57it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 517.24it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 515.52it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 497.49it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 992.73it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 474.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 476.63it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 798.61it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 532.41it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1003.90it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 491.08it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1003.90it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.36it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1005.83it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 457.34it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 910.82it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 518.90it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.62it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.95it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 884.87it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1076.57it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 491.25it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 968.66it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 522.78it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1003.90it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.60it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 953.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 456.80it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.69it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 962.22it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 992.97it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 432.54it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 335.52it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 829.57it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 996.75it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.69it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1054.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 425.26it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.92it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1017.05it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1020.76it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1012.38it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 969.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 443.94it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.60it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 508.89it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1013.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 419.47it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 997.69it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 997.46it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 380.02it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 993.44it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 488.90it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.68it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 428.73it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 411.77it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.98it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 464.33it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 502.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 962.88it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 757.92it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 996.98it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 995.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 997.93it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 440.39it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 432.45it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 944.45it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1005.83it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 325.29it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 361.05it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 502.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.36it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1072.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 997.22it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 991.56it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 837.69it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 992.26it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 588.26it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 492.00it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.23it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 861.08it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]

  [2981/2981] q.999…
  Found 18 matching cases for max_min_chunker

── Chunker: recursive_semantic ─────────────────────────────

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 502.37it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 993.91it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.45it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 981.81it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1011.16it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 485.28it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 493.74it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1028.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 506.74it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.26it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 488.11it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 343.91it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.98it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1007.76it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.37it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.26it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 997.69it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 506.31it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1016.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 481.61it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.20it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1779.51it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.14it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.25it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1022.75it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.89it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 487.77it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 482.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 334.90it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1018.53it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 320.62it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.74it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.88it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 424.22it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.55it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 710.06it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 997.69it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 646.87it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.18it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 526.92it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.03it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 494.84it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1048.05it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1018.78it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.88it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 979.52it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 972.48it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.57it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 488.79it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.76it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.30it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1059.17it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.60it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.52it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.09it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.66it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.67it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.70it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.88it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.34it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.27it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 983.19it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1017.05it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1002.94it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 346.87it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.09it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 330.39it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1021.26it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 984.58it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.58it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 978.15it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 526.79it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 488.39it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.22it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 997.22it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.51it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.83it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.10it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.70it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1015.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.91it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.79it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.34it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 519.74it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 996.04it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.91it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.37it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.43it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 491.65it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.57it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.04it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.82it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 530.39it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 493.85it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 525.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 473.45it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1137.28it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1059.97it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1007.52it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 505.52it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 395.28it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.12it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 994.85it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 475.60it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 502.07it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.52it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.92it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 984.12it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.67it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.70it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.27it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.78it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.27it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.51it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.20it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.54it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1019.02it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 496.19it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.30it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.88it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.24it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.40it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.97it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.17it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.76it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 494.20it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 331.46it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 493.74it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 993.20it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.60it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.12it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 996.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 489.47it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 401.60it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 335.12it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.51it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1015.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.79it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 510.94it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.51it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 331.59it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.54it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 388.61it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 512.81it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1015.57it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 520.84it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.50it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.05it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 330.96it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.56it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 941.69it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 361.24it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.97it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.75it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 331.85it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 506.93it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 985.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.20it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.99it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 373.39it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 336.08it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 497.19it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 985.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 662.19it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 982.27it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.69it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 983.65it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1018.78it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.03it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.50it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.02it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 505.09it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.98it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 507.23it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.49it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 949.58it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1014.59it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 483.44it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.33it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 334.39it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1006.07it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 387.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.90it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.12it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.03it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.36it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 651.59it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1022.00it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.40it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 971.80it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 494.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.39it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.02it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1014.10it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1015.82it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.38it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.15it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.74it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.10it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.83it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.45it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.10it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 470.69it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.92it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1015.32it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.81it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 983.42it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.22it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.64it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.45it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.60it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 520.00it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]

  Found 32 matching cases for recursive_semantic

── Chunker: sequential_hac_chunker ─────────────────────────────

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 919.00it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 527.78it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 959.36it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.85it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1178.51it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.61it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.10it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.83it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.12it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.36it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.11it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.33it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.49it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.38it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.27it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.83it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 493.80it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.16it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.27it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.18it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 523.57it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.27it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 522.98it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1013.12it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.36it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 244.52it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 948.94it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.08it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1076.57it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 335.01it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.12it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.74it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 242.35it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 494.15it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1021.75it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.20it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 321.48it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1011.65it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 502.55it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 994.15it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 321.60it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.20it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1015.32it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.41it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.52it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1016.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.94it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.60it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 496.84it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 990.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 512.44it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1014.10it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.20it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1817.29it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 519.03it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.02it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 398.02it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 997.69it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 896.03it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1017.79it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.59it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1043.36it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 342.90it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 249.85it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 994.15it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 506.01it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.66it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 983.19it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1011.65it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.64it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 967.32it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 502.61it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 997.69it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.58it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 328.89it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 940.01it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.51it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 508.83it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 457.34it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 483.66it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.79it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 284.34it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 514.76it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1072.99it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.12it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 460.26it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1070.52it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 414.29it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.20it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1007.52it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1010.19it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.29it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 991.56it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 996.27it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 898.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1138.83it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 521.42it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.79it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1016.06it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1014.10it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 462.39it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 985.50it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 520.90it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.83it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 342.31it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 733.65it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1784.05it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.99it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.36it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 735.33it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 989.92it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.68it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1009.95it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.10it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1047.79it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 529.25it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.51it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.60it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 343.82it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.36it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1119.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.98it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 521.81it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.82it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1143.49it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1020.02it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.97it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.12it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.27it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 740.39it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 496.25it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 857.56it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 988.99it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 332.72it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 220.78it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.88it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 343.09it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 674.22it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 852.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 205.32it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 405.68it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1007.52it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 502.19it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1036.14it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 308.40it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 3/3 [00:00<00:00, 240.60it/s]
Compute Scores: 100%|██████████| 3/3 [00:01<00:00,  2.18it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.83it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 338.93it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1003.42it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 199.85it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1049.36it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 513.69it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.55it/s]
pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 180.73it/s]
Compute Scores: 100%|██████████| 2/2 [00:00<00:00,  2.25it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 740.26it/s]
pre tokenize: 100%|██████████| 2/2 [00:00<00:00, 328.45it/s]
Compute Scores: 100%|██████████| 2/2 [00:00<00:00,  3.22it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1005.11it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 200.70it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 480.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 667.14it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 193.99it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1013.36it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 335.87it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 941.91it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1042.32it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1069.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1103.18it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 798.76it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.35it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 671.09it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.31it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.43it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 688.38it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 511.38it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.45it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 994.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.27it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 504.85it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 535.47it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 855.81it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 497.60it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 949.37it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.29it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 332.17it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.84it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1004.86it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1007.28it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 725.78it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 536.97it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 341.64it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1052.26it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1004.38it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.88it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.10it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.74it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 337.71it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1002.22it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 450.03it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.27it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 996.27it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 493.33it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.83it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 480.17it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 913.79it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 524.68it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 976.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 740.26it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 510.26it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1002.46it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 401.25it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 252.61it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1092.84it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 644.88it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1005.35it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.69it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 993.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 872.18it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1008.97it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 316.91it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1771.99it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 506.93it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 987.13it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 487.48it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 993.44it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 506.50it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1005.11it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.44it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 741.44it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1031.05it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 506.01it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 334.47it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 443.09it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.27it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.89it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1020.02it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 508.40it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1009.95it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 333.17it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 511.06it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 894.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 505.76it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 502.13it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 995.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1045.96it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1000.79it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 323.96it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 491.94it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 493.68it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 931.45it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 960.67it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 280.16it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 531.26it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 517.05it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1008.49it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 347.10it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 497.25it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 944.24it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 319.76it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 882.83it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 513.25it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 442.81it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 864.09it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 468.22it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 615.72it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.81it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 415.69it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 985.50it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 455.36it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1193.60it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 494.20it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1005.59it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 547.85it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 480.34it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 503.88it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 718.57it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 532.14it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 991.09it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1001.03it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 461.12it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 490.68it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 749.38it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.67it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 261.44it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 968.44it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 495.37it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.02it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 994.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 775.86it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 511.06it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 497.60it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 498.43it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 816.17it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 996.75it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 793.02it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 499.74it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 501.17it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.60it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 497.84it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.60it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.39it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1023.50it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 335.97it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 999.83it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 998.17it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 513.50it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1013.12it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 997.22it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1022.50it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 987.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 490.50it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.69it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 490.91it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1090.28it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<?, ?it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 502.31it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 977.47it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 420.57it/s]

  Found 5 matching cases for sequential_hac_chunker


Znaleziono łącznie: 88 pasujących przypadków.

## 6. Podsumowanie tekstowe

In [7]:
analysis.print_summary(cases, SCORE_TOL, RERANKER_THRESHOLD)

========================================================================
SUMMARY  —  88 matching case(s)
  |retrieval_diff| ≤ 0.02  AND  |reranker_diff| > 0.5
========================================================================

Chunker: fixed_size  (33 case(s))

  Query q.1000: What natural phenomenon is described as having a certain beauty when it is in a state that…
  Non-merged HIT chunks:
    [55164]  ret=0.5557  rer=-2.8672
      irst made all even and uniform, they become it well nevertheless, and have a certain peculiar property, to stir the appe…

  Merged conflicting chunks (embedding≈, reranker≠):
    [50109]  ret=0.5713  rer=-4.9453
      roth of a foaming wild boar, and many other like things, though by themselves considered, they are far from any beauty, …

  Query q.1039: What physical discomfort was Mr. Casaubon experiencing in the library?
  Non-merged HIT chunks:
    [57152]  ret=0.5259  rer=3.4805
      rity of the outdoor snow. As she laid the cameo-cases on the table in the bow-window, she unconsciously kept her hands o…

  Merged conflicting chunks (embedding≈, reranker≠):
    [51939]  ret=0.5205  rer=-1.5459
      iffering white of the fur which itself seemed to wind about her neck and cling down her blue-gray pelisse with a tendern…

  Query q.1123: Who was the overseer known for his cruelty and profanity towards the slaves on the plantat…
  Non-merged HIT chunks:
    [65673]  ret=0.4929  rer=1.3037
      him talk. Scarce a sentence escaped him but that was commenced or concluded by some horrid oath. The field was the place…

  Merged conflicting chunks (embedding≈, reranker≠):
    [59841]  ret=0.4854  rer=-1.1172
      age nor sex finds any favor. Mr. Severe, the overseer, used to stand by the door of the quarter, armed with a large hick…
    [59842]  ret=0.5024  rer=-5.9258
      in the midst of her crying children, pleading for their mother’s release. He seemed to take pleasure in manifesting his …
    [59843]  ret=0.4797  rer=-0.6909
      d of blood and of blasphemy. From the rising till the going down of the sun, he was cursing, raving, cutting, and slashi…

  Query q.1180: What topics did Anne discuss with Captain Benwick to engage him in conversation?
  Non-merged HIT chunks:
    [68608]  ret=0.7007  rer=-1.3447
      le Captains Wentworth and Harville led the talk on one side of the room, and by recurring to former days, supplied anecd…

  Merged conflicting chunks (embedding≈, reranker≠):
    [62500]  ret=0.6968  rer=-2.3301
      the talk on one side of the room, and by recurring to former days, supplied anecdotes in abundance to occupy and enterta…

  Query q.1189: What caught the Admiral's attention and sparked his humorous comments during his encounter…
  Non-merged HIT chunks:
    [68909]  ret=0.6484  rer=0.9897
      o Camden Place, and in walking up Milsom Street she had the good fortune to meet with the Admiral. He was standing by hi…

  Merged conflicting chunks (embedding≈, reranker≠):
    [62770]  ret=0.6494  rer=-1.7168
      y forming into a little knot of the navy, Mrs Croft looking as intelligent and keen as any of the officers around her. A…

  Query q.1238: What solution did Elizabeth agree to in order to help her sister's worsening condition?
  Non-merged HIT chunks:
    [70097]  ret=0.5552  rer=-0.4685
      Elizabeth joined them again only to say that her sister was worse, and that she could not leave her. Bingley urged Mr. J…
    [70098]  ret=0.5234  rer=-2.0098
      the morning, if Miss Bennet were not decidedly better. Bingley was quite uncomfortable; his sisters declared that they w…

  Merged conflicting chunks (embedding≈, reranker≠):
    [63852]  ret=0.5225  rer=-3.0352
      f to his feelings than by giving his housekeeper directions that every possible attention might be paid to the sick lady…

  Query q.1349: How did Elinor feel upon realizing that Edward was now married to Lucy?
  Non-merged HIT chunks:
    [74599]  ret=0.5850  rer=0.8613
      nd consequently before he could be in possession of the living, surprised her a little at first. But she soon saw how li…

  Merged conflicting chunks (embedding≈, reranker≠):
    [67934]  ret=0.5679  rer=-2.5352
      ffer consolation. She now found that she had erred in relying on Elinor’s representation of herself; and justly conclude…
    [67936]  ret=0.5898  rer=-0.0552
      ound the difference between the expectation of an unpleasant event, however certain the mind may be told to consider it,…
    [67938]  ret=0.5791  rer=-0.7202
      k of delay. They were married, married in town, and now hastening down to her uncle’s. What had Edward felt on being wit…
    [67939]  ret=0.5840  rer=-1.5215
      ucy, the active, contriving manager, uniting at once a desire of smart appearance with the utmost frugality, and ashamed…

  Query q.1420: How did Roderick and his companions manage to treat Rattlin's leg injury on the ship?
  Non-merged HIT chunks:
    [80254]  ret=0.5161  rer=-0.5088
      I signified my concurrence; and Rattlin was so overjoyed that, shaking us both by the hands, he swore nobody else should…
    [80255]  ret=0.5278  rer=-2.8613
      hteen-tailed bandage, and put the leg in a box, secundam artem. Everything succeeded according to our wish, and we had t…

  Merged conflicting chunks (embedding≈, reranker≠):
    [73161]  ret=0.5142  rer=-3.7617
      box, secundam artem. Everything succeeded according to our wish, and we had the satisfaction of not only preserving the …

  Query q.1596: What action did Katerina Ivanovna take after the incident with the banknote and before lea…
  Non-merged HIT chunks:
    [87429]  ret=0.5840  rer=-0.2084
      y, to the astonishment of every one, for nobody believed that he had the money untouched. He’d no sooner paid it than he…

  Merged conflicting chunks (embedding≈, reranker≠):
    [79679]  ret=0.5742  rer=-1.4033
      and, three weeks later, softening of the brain set in, and he died five days afterwards. He was buried with military hon…

  Query q.1653: How did Augustine's false notion of spiritual things hinder his understanding of the natur…
  Non-merged HIT chunks:
    [92056]  ret=0.5029  rer=-0.9141
      But I saw not yet, whereon this weighty matter turned in Thy wisdom, O Thou Omnipotent, who only doest wonders; and my m…

  Merged conflicting chunks (embedding≈, reranker≠):
    [83874]  ret=0.5142  rer=-5.0391
      did of itself flash into mine eyes, and I turned away my panting soul from incorporeal substance to lineaments, and colo…

  Query q.167: Who came to bring Scrooge home and described how kind their father had become, leading to …
  Non-merged HIT chunks:
    [8634]  ret=0.6299  rer=-0.3008
      He was not reading now, but walking up and down despairingly. Scrooge looked at the Ghost, and with a mournful shaking o…

  Merged conflicting chunks (embedding≈, reranker≠):
    [7833]  ret=0.6118  rer=-3.6172
      ight. I should like to have given him something: that’s all.” The Ghost smiled thoughtfully, and waved its hand: saying …
    [7834]  ret=0.6167  rer=-3.0879
      He only knew that it was quite correct; that everything had happened so; that there he was, alone again, when all the ot…

  Query q.1786: What strategy does Mlle. Blanche seem likely to employ in dealing with the Grandmother's u…
  Non-merged HIT chunks:
    [101579]  ret=0.6016  rer=-0.6299
      the neck in the affair, had not wholly lost courage; and I felt sure that Mlle. Blanche also—Mlle. Blanche who was not o…

  Merged conflicting chunks (embedding≈, reranker≠):
    [92542]  ret=0.5918  rer=-1.9346
      General any money, that declaration was not a complete ground for the abandonment of hope. Certainly De Griers, who, wit…

  Query q.1796: What plan does Mlle. Blanche have in mind regarding the General and Mr. Astley?
  Non-merged HIT chunks:
    [101834]  ret=0.5532  rer=-0.4863
      ocket. Quant à moi, je veux cinquante mille francs de rente, et alors——” “But what about the General?” I interrupted. “T…

  Merged conflicting chunks (embedding≈, reranker≠):
    [92766]  ret=0.5483  rer=-1.3271
      I felt that the scene was to be changed only for a time. “Within a month from now,” I kept thinking to myself, “I shall …
    [92768]  ret=0.5371  rer=-1.5010
      our pocket. Quant à moi, je veux cinquante mille francs de rente, et alors——” “But what about the General?” I interrupte…

  Query q.1979: What two qualifications must the murderer have, according to Poirot's deductions?
  Non-merged HIT chunks:
    [108966]  ret=0.5073  rer=0.5718
      “And the murderer switched it on. Then he must have been in the room at that minute?” “Possibly. But we must not exclude…

  Merged conflicting chunks (embedding≈, reranker≠):
    [99207]  ret=0.4934  rer=-1.5361
      was already dead. It was the dictaphone speaking—not the man.” “And the murderer switched it on. Then he must have been …

  Query q.206: How did Hank Morgan ensure that the platform for the miracle performance was impressive an…
  Non-merged HIT chunks:
    [9607]  ret=0.4744  rer=-0.5723
      About two hundred yards off, in the flat, we built a pen of scantlings, about four feet high, and laid planks on it, and…
    [9608]  ret=0.4958  rer=-2.1465
      r your head guest; then you can turn yourself loose and play your effects for all they are worth. I know the value of th…
    [9611]  ret=0.4700  rer=-6.7930
      he region which was under my ban must be clear; the bells would then cease from tolling, and this sign should be permiss…

  Merged conflicting chunks (embedding≈, reranker≠):
    [8725]  ret=0.4561  rer=-8.3281
      s a half hour it continued to flow, and then it solidified itself, and you could have walked upon a pavement of human he…

  Query q.2061: Why does Basil express concern about Dorian's influence on his friends and society?
  Non-merged HIT chunks:
    [112048]  ret=0.4915  rer=-2.0566
      “Dorian,” cried Hallward, “that is not the question. England is bad enough I know, and English society is all wrong. Tha…

  Merged conflicting chunks (embedding≈, reranker≠):
    [101979]  ret=0.4807  rer=-4.2578
      acies of their betters in order to try and pretend that they are in smart society and on intimate terms with the people …

  Query q.216: What surprising discovery did Smith make upon opening the volume they chose to read?
  Non-merged HIT chunks:
    [10577]  ret=0.5117  rer=-0.3420
      ustoms of this people, especially their ideas concerning The House, which appeared to be an object of almost religious r…

  Merged conflicting chunks (embedding≈, reranker≠):
    [9593]  ret=0.4993  rer=-2.2852
      re, or giving expression to any more "extraordinary delusions." On opening the volume I was greatly surprised to find th…

  Query q.2169: what should one consider when consuming food or drink?
  Non-merged HIT chunks:
    [114512]  ret=0.5684  rer=-3.8750
      Then an old man, a keeper of an inn, said, Speak to us of Eating and Drinking. And he said: Would that you could live on…

  Merged conflicting chunks (embedding≈, reranker≠):
    [104207]  ret=0.5508  rer=-4.4805
      who deem yourself a giver, are but a witness. And you receivers—and you are all receivers—assume no weight of gratitude,…

  Query q.2313: How does Dr. Watson react to Sherlock Holmes' deductions regarding his brother?
  Non-merged HIT chunks:
    [122187]  ret=0.5781  rer=-1.3936
      I sprang from my chair and limped impatiently about the room with considerable bitterness in my heart. “This is unworthy…

  Merged conflicting chunks (embedding≈, reranker≠):
    [111252]  ret=0.5645  rer=-2.5918
      my unhappy brother, and you now pretend to deduce this knowledge in some fanciful way. You cannot expect me to believe t…

  Query q.2555: How did the lieutenant interpret the king's unspoken command to call the musketeers?
  Non-merged HIT chunks:
    [130280]  ret=0.5811  rer=0.1044
      , casting from time to time a side glance at the lieutenant. “He is the very image of his father,” continued the latter,…

  Merged conflicting chunks (embedding≈, reranker≠):
    [118649]  ret=0.5659  rer=-1.3916
      ength to the entrance door, and they so thoroughly remarked all I have said, that they saw your majesty’s lips articulat…

  Query q.2564: What did D'Artagnan request from Charles as payment for his services?
  Non-merged HIT chunks:
    [131076]  ret=0.5986  rer=0.4512
      Charles. “That is a gallant proposal, and a gallant man, is he not, duke?” “Upon my honor, yes, sire,” and he drew his s…

  Merged conflicting chunks (embedding≈, reranker≠):
    [119365]  ret=0.5850  rer=-0.5425
      for there is nothing in the world but the general’s sword which is worth as much as himself.” “Odds fish! as my father s…

  Query q.2571: What condition does King Louis XIV set for D'Artagnan before making him a knight of the ki…
  Non-merged HIT chunks:
    [131678]  ret=0.5693  rer=-1.3359
      comer would perform for four thousand livres.” Louis XIV. began to laugh. “You are a true Gascon, Monsieur d’Artagnan; y…
    [131680]  ret=0.5298  rer=-1.2539
      you?” “Why, yes, sire. My friend Athos is quite covered with orders, and that dazzles me.” “You shall be a knight of my …

  Merged conflicting chunks (embedding≈, reranker≠):
    [119904]  ret=0.5146  rer=-3.0137
      edicts, and those of my father. You will reorganize the service as soon as possible.” “Yes, sire.” “You will not again q…

  Query q.2644: Why did Zarathustra express his weariness and desire to descend into the deep?
  Non-merged HIT chunks:
    [133765]  ret=0.5605  rer=-0.4619
      1.When Zarathustra was thirty years old, he left his home and the lake of his home, and went into the mountains. There h…

  Merged conflicting chunks (embedding≈, reranker≠):
    [121788]  ret=0.5459  rer=-2.3203
      ous in their folly, and the poor happy in their riches. Therefore must I descend into the deep: as thou doest in the eve…
    [121789]  ret=0.5645  rer=-2.2539
      and carry everywhere the reflection of thy bliss! Lo! This cup is again going to empty itself, and Zarathustra is again …

  Query q.2752: What amount of money did Mazarin initially offer D'Artagnan for his mission to Boulogne?
  Non-merged HIT chunks:
    [139264]  ret=0.5376  rer=-0.1226
      pouted out his lower lip in a most extraordinary manner. “I reply, my lord, ’tis but little, as certainly I shall not go…

  Merged conflicting chunks (embedding≈, reranker≠):
    [126721]  ret=0.5522  rer=-5.3867
      sent it?” “You will know when you reach London; at London you may tear off the outer envelope.” “And what are my instruc…
    [126725]  ret=0.5493  rer=-4.6797
      er my duty to her majesty the queen?” “Her majesty is asleep and you must set off directly,” replied Mazarin; “go, pray,…

  Query q.2908: What ultimatum does Andrew give Scottie regarding his actions once he enters the house?
  Non-merged HIT chunks:
    [156171]  ret=0.4907  rer=-1.1650
      nks to leave the house and ride away with you. Understand, when you get inside the house, there'll be a big temptation t…

  Merged conflicting chunks (embedding≈, reranker≠):
    [142069]  ret=0.4771  rer=-3.4844
      hance indeed, this leaving of Dozier helpless on the floor; but he risked it. He whispered to the marshal that he would …
    [142072]  ret=0.4736  rer=-3.0273
      ve done to the way you hate Dozier, and I won't hold a grudge. And I'll tell you the chance you've got. You see these ro…
    [142073]  ret=0.4763  rer=-1.9736
      l persuade that crowd of drunks to leave the house and ride away with you. Understand, when you get inside the house, th…
    [142074]  ret=0.4919  rer=-2.5801
      o move fast, I pull the trigger. Remember it, Scottie. For as sure as there's a hell, I'll send you into it head first, …

  Query q.2990: Where does the narrator find Mr. Heathcliff when they go to inform him of Catherine Linton…
  Non-merged HIT chunks:
    [158761]  ret=0.6011  rer=-0.0463
      Retracing the course of Catherine Linton, I fear we have no right to think she is; but we’ll leave her with her Maker. T…

  Merged conflicting chunks (embedding≈, reranker≠):
    [144440]  ret=0.5864  rer=-1.0186
      me as something heterodox. She proceeded:  Retracing the course of Catherine Linton, I fear we have no right to think sh…

  Query q.382: Who was identified by Defarge as a secret and unaccused prisoner in the Bastille?
  Non-merged HIT chunks:
    [16181]  ret=0.6704  rer=0.4387
      nted Tribunal sitting, before which the prisoners were brought singly, and by which they were rapidly ordered to be put …

  Merged conflicting chunks (embedding≈, reranker≠):
    [14688]  ret=0.6636  rer=-1.6074
      nal sitting, before which the prisoners were brought singly, and by which they were rapidly ordered to be put forth to b…

  Query q.524: Why does Mr. Blake mention the importance of keeping the weeds away from the garden plants…
  Non-merged HIT chunks:
    [21650]  ret=0.5381  rer=-1.9824
      se," said Mr. Blake. "Crows are more plentiful in the country and—" "I know how to keep them away!" cried Mab. "How?" as…

  Merged conflicting chunks (embedding≈, reranker≠):
    [19682]  ret=0.5259  rer=-3.7715
      ng beans, which is the sort in your garden, Mab, there are the larger or lima beans, which are very good to eat. I have …
    [19685]  ret=0.5283  rer=-3.1367
      e soil nicely pulverized and damp." "What do the weeds do to the beans?" asked Mab. "Well, the weeds grow faster than th…
    [19686]  ret=0.5415  rer=-4.3984
      eat. "So, in order that you might grow well and strong, we would have to take the giant away. It's the same with weeds. …

  Query q.561: Where did David Copperfield and his fellow-travelers find a lodging for Peggotty?
  Non-merged HIT chunks:
    [24356]  ret=0.5967  rer=0.1824
      shoes off, lying on the pavement at a considerable distance. When we got to our journey’s end, our first pursuit was to …

  Merged conflicting chunks (embedding≈, reranker≠):
    [22135]  ret=0.5889  rer=-1.7236
      ho were coming in the opposite direction, I should enter on a task of some difficulty. Therefore I had better leave her …

  Query q.765: How did the king describe the natives of Gulliver's country?
  Non-merged HIT chunks:
    [36627]  ret=0.4746  rer=-4.7031
      e procurement of any one station among you; much less, that men are ennobled on account of their virtue; that priests ar…

  Merged conflicting chunks (embedding≈, reranker≠):
    [33257]  ret=0.4614  rer=-5.6445
      from all you have said, how any one perfection is required toward the procurement of any one station among you; much les…

  Query q.798: What unique clothing description is given to the man on the shore?
  Non-merged HIT chunks:
    [37711]  ret=0.5474  rer=0.0439
      engines and let her drift down. The man on the shore began to shout, urging us to land. ‘We have been attacked,’ screame…

  Merged conflicting chunks (embedding≈, reranker≠):
    [34266]  ret=0.5410  rer=-7.3125
      sunshine made him look extremely gay and wonderfully neat withal, because you could see how beautifully all this patchin…

  Query q.855: What does Mr. Rochester request Jane to bring him from the dining-room?
  Non-merged HIT chunks:
    [39979]  ret=0.5293  rer=1.8965
      in a quiet island with only you; and trouble, and danger, and hideous recollections removed from me.” “Can I help you, s…

  Merged conflicting chunks (embedding≈, reranker≠):
    [36338]  ret=0.5415  rer=-4.2344
      long, sir; it must be near eleven o’clock. Oh, are you aware, Mr. Rochester, that a stranger has arrived here since you …
    [36339]  ret=0.5166  rer=-3.6270
      .”  Mr. Rochester was standing near me; he had taken my hand, as if to lead me to a chair. As I spoke he gave my wrist a…
    [36341]  ret=0.5127  rer=1.0879

## 7. Wyniki jako DataFrame

In [9]:
import pandas as pd

rows = []
for c in cases:
    for mc in c.merged_close_chunks:
        rows.append({
            "query_id":            c.query_id,
            "query_text":          c.query_text[:80] + "…" if len(c.query_text) > 80 else c.query_text,
            "chunker":             c.chunker_name,
            "nm_best_ret":         round(c.nonmerged_best_retrieval, 4),
            "merged_chunk_id":     mc.chunk_id,
            "merged_ret":          round(mc.score_retrieval, 4),
            "merged_rer":          round(mc.score_reranker,  4),
            "ret_diff":            round(abs(mc.score_retrieval - c.nonmerged_best_retrieval), 4),
            "merged_chunk_preview": mc.contents_preview[:80],
        })

df = pd.DataFrame(rows)
if df.empty:
    print("Brak wyników — spróbuj zwiększyć SCORE_TOL lub zmniejszyć RERANKER_THRESHOLD")
else:
    print(f"Wierszy: {len(df)},  unikalnych pytań: {df['query_id'].nunique()}")
    display(df)

Wierszy: 128,  unikalnych pytań: 25

,query_id,query_text,chunker,nm_best_ret,merged_chunk_id,merged_ret,merged_rer,ret_diff,merged_chunk_preview
0,q.triviaqa-span-annotated.165845,What was the word for an Indian soldier servin...,fixed_size,0.4688,5306,0.4580,-6.0977,0.0107,"rust remains. August 2, 1858 Parliament puts I..."
1,q.triviaqa-span-annotated.263842,Which British army regiment are known as Sappers,fixed_size,0.3855,12535,0.3887,-6.8359,0.0032,am Tuesday we had arrived at Camp Bastion to s...
2,q.triviaqa-span-annotated.288148,"Batting, Cornerstones, Sashing and Layer Cake ...",fixed_size,0.4146,14039,0.3972,-4.9531,0.0173,few large pieces of fabric pieced to slightly ...
3,q.triviaqa-span-annotated.298469,"What is the next in this sequence: Madison, Mo...",fixed_size,0.4187,4417,0.3989,-5.7383,0.0198,rural coal-mining towns in Eastern Kentucky. S...
4,q.triviaqa-span-annotated.300459,What type of hat was famously worn by Che Guev...,fixed_size,0.4546,5864,0.4727,-4.4453,0.0181,"GREEN BERET is also called ""green beanie"" and ..."
...,...,...,...,...,...,...,...,...,...
123,q.triviaqa-span-annotated.80584,In the 2001 official UK national census what r...,dense_x_retrieval,0.5073,127342,0.5073,-9.5156,0.0000,
124,q.triviaqa-span-annotated.80584,In the 2001 official UK national census what r...,dense_x_retrieval,0.5073,127347,0.5073,-9.5156,0.0000,
125,q.triviaqa-span-annotated.80584,In the 2001 official UK national census what r...,dense_x_retrieval,0.5073,127358,0.5073,-9.5156,0.0000,
126,q.triviaqa-span-annotated.80584,In the 2001 official UK national census what r...,dense_x_retrieval,0.5073,127577,0.5073,-9.5156,0.0000,
127,q.triviaqa-span-annotated.80584,In the 2001 official UK national census what r...,dense_x_retrieval,0.5073,127582,0.5073,-9.5156,0.0000,

## 8. Sortowanie i filtrowanie

In [10]:
if not df.empty:
    # Najwyższy reranker score merged na górze
    display(df.sort_values("merged_rer", ascending=False).reset_index(drop=True))

,query_id,query_text,chunker,nm_best_ret,merged_chunk_id,merged_ret,merged_rer,ret_diff,merged_chunk_preview
0,q.triviaqa-span-annotated.300459,What type of hat was famously worn by Che Guev...,fixed_size,0.4546,5864,0.4727,-4.4453,0.0181,"GREEN BERET is also called ""green beanie"" and ..."
1,q.triviaqa-span-annotated.36766,"January King, Meteor, and Salarite are varieti...",fixed_size,0.3694,25352,0.3562,-4.5352,0.0132,abbage Cool-Season Vegetables: How to Grow Cab...
2,q.triviaqa-span-annotated.288148,"Batting, Cornerstones, Sashing and Layer Cake ...",fixed_size,0.4146,14039,0.3972,-4.9531,0.0173,few large pieces of fabric pieced to slightly ...
3,q.triviaqa-span-annotated.57518,In which Bond film does Charles Grey play the ...,fixed_size,0.4360,25990,0.4487,-5.1602,0.0127,D IS BACK - Sean Connery is BOND [British adva...
4,q.triviaqa-span-annotated.292764,Suint is a natural grease formed from the drie...,max_min_chunker,0.4248,20980,0.4204,-5.6836,0.0044,The breed's double coat enables it to adapt to...
...,...,...,...,...,...,...,...,...,...
123,q.triviaqa-span-annotated.335736,"Who famously ate peanut butter, banana, and ba...",dense_x_retrieval,0.4583,149980,0.4412,-10.0156,0.0171,
124,q.triviaqa-span-annotated.335736,"Who famously ate peanut butter, banana, and ba...",dense_x_retrieval,0.4583,149960,0.4412,-10.0156,0.0171,
125,q.triviaqa-span-annotated.335736,"Who famously ate peanut butter, banana, and ba...",dense_x_retrieval,0.4583,149961,0.4412,-10.0156,0.0171,
126,q.triviaqa-span-annotated.270507,Which popular garden bird has the Latin name C...,dense_x_retrieval,0.4946,-1,0.4873,-10.0469,0.0073,
127,q.triviaqa-span-annotated.279420,What is the more common name for the confectio...,dense_x_retrieval,0.4814,-1,0.4744,-10.0859,0.0071,

In [11]:
# Filtruj: chunki gdzie reranker merged > 3.0
if not df.empty:
    high = df[df["merged_rer"] > 3.0].sort_values("merged_rer", ascending=False)
    print(f"Chunki z reranker merged > 3.0: {len(high)}")
    display(high.reset_index(drop=True))

Chunki z reranker merged > 3.0: 0

Empty DataFrame
Columns: [query_id, query_text, chunker, nm_best_ret, merged_chunk_id, merged_ret, merged_rer, ret_diff, merged_chunk_preview]
Index: []

## 9. Wykres — liczba przypadków per chunker

In [13]:
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Collecting matplotlib
  Downloading matplotlib-3.10.9-cp312-cp312-win_amd64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.62.1-cp312-cp312-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.0-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Collecting numpy>=1.23 (from matplotlib)
  Using cached numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-12.2.0-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.9-cp312-cp312-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ------- -------------------------------- 1.6/8.2 MB 10.5 MB/s eta 0:00:01
   -------------------- ------------------- 4.2/8.2 MB 12.0 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.2 MB 12.5 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 12.4 MB/s eta 0:00:00
Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.62.1-cp312-cp312-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.5.0-cp312-cp312-win_amd64.whl (73 kB)
Using cached numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
Using cached pillow-12.2.0-cp312-cp312-win_amd64.whl (7.1 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, numpy, kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 kiwisolver-1.5.0 matplotlib-3.10.9 numpy-2.4.4 pillow-12.2.0 pyparsing-3.3.2

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [15]:
import matplotlib.pyplot as plt

if not df.empty:
    counts = df.groupby("chunker")["query_id"].nunique().sort_values(ascending=False)
    fig, ax = plt.subplots(figsize=(max(6, len(counts)*1.8), 4))
    counts.plot(kind="bar", ax=ax, color="#5c7cfa", edgecolor="#3a5de0")
    ax.set_title(
        f"Pytania: non-merged lepszy, merged miał bliski chunk (±{SCORE_TOL}) "
        f"z wysokim reranker (>{RERANKER_THRESHOLD})"
    )
    ax.set_xlabel("Chunker")
    ax.set_ylabel("Liczba unikalnych pytań")
    ax.tick_params(axis="x", rotation=30)
    for i, v in enumerate(counts):
        ax.text(i, v + 0.05, str(v), ha="center")
    plt.tight_layout()
    plt.show()

ModuleNotFoundError: No module named 'matplotlib'

## 10. Scatter — retrieval vs reranker score (merged chunki)

In [ ]:
import matplotlib.pyplot as plt

if not df.empty:
    chunkers = df["chunker"].unique()
    colors   = ["#5c7cfa", "#f59f00", "#63e6be", "#f03e3e", "#da77f2"]

    fig, ax = plt.subplots(figsize=(7, 5))
    for i, ch in enumerate(chunkers):
        sub = df[df["chunker"] == ch]
        ax.scatter(sub["merged_ret"], sub["merged_rer"],
                   label=ch, color=colors[i % len(colors)],
                   alpha=0.75, s=60, edgecolors="white", linewidths=0.5)

    ax.axhline(RERANKER_THRESHOLD, color="red",  linestyle="--", lw=1.2,
               label=f"reranker threshold ({RERANKER_THRESHOLD})")
    ax.axvspan(
        df["nm_best_ret"].min() - SCORE_TOL,
        df["nm_best_ret"].max() + SCORE_TOL,
        alpha=0.06, color="steelblue", label=f"retrieval ±{SCORE_TOL} band",
    )
    ax.set_xlabel("Score Retrieval (merged chunk)")
    ax.set_ylabel("Score Reranker (merged chunk)")
    ax.set_title("Merged chunki spełniające oba warunki")
    ax.legend(fontsize=8)
    plt.tight_layout()
    plt.show()

## 11. Podgląd pojedynczego przypadku

In [ ]:
CASE_IDX = 0   # zmień żeby zobaczyć inny przypadek

if cases:
    c = cases[CASE_IDX]
    print(f"Query ID  : {c.query_id}")
    print(f"Chunker   : {c.chunker_name}")
    print(f"Pytanie   : {c.query_text}")
    print()
    print("Non-merged — zwrócone relevantne chunki:")
    for ch in c.nonmerged_hit_chunks:
        print(f"  [{ch.chunk_id}]  ret={ch.score_retrieval:.4f}  rer={ch.score_reranker:.4f}")
        print(f"    {ch.contents_preview}")
    print()
    print(f"Merged — spełniające (ret±{SCORE_TOL}, rer>{RERANKER_THRESHOLD}):")
    for ch in c.merged_close_chunks:
        diff = abs(ch.score_retrieval - c.nonmerged_best_retrieval)
        print(f"  [{ch.chunk_id}]  ret={ch.score_retrieval:.4f} (diff={diff:.4f})  rer={ch.score_reranker:.4f}")
        print(f"    {ch.contents_preview}")
else:
    print("Brak przypadków.")

## 12. Szybka re-analiza z innymi parametrami

Modele są już załadowane — ponowna analiza nie wymaga ładowania modeli.

In [ ]:
# Zmień progi i uruchom ponownie bez przeładowania modeli
cases2 = analysis.analyze(
    dataset_slug       = DATASET,
    data_root          = DATA_ROOT,
    score_tol          = 0.05,         # ← zmień
    reranker_threshold = 0.5,          # ← zmień
    verbose            = False,
)
print(f"Nowe parametry → {len(cases2)} przypadków")
analysis.print_summary(cases2, 0.05, 0.5)

## 13. Zapis wyników do JSON

In [ ]:
OUTPUT_FILE = f"results_{DATASET}_tol{SCORE_TOL}_rer{RERANKER_THRESHOLD}.json"
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump([asdict(c) for c in cases], f, indent=2, ensure_ascii=False)
print(f"Zapisano {len(cases)} przypadków → {OUTPUT_FILE}")